#ifndef GSPH_COMPILE_CONFIG_H_
#define GSPH_COMPILE_CONFIG_H_

#ifndef GSPH_HEADLESS
#define GSPH_HEADLESS 0
#endif

#ifndef GSPH_USE_REGISTER_SMS
#define GSPH_USE_REGISTER_SMS 1
#endif

#ifndef GSPH_ENABLE_HISTORICAL_ISSAME
#define GSPH_ENABLE_HISTORICAL_ISSAME 1
#endif

#ifndef GSPH_ENABLE_SMS_LOCAL_MERGE
#define GSPH_ENABLE_SMS_LOCAL_MERGE 1
#endif

#ifndef GSPH_ENABLE_SMS_LOCAL_MERGE_FORCE
#define GSPH_ENABLE_SMS_LOCAL_MERGE_FORCE 0
#endif

#ifndef GSPH_ENABLE_SAME_CELL_PAIR_FORCE
#define GSPH_ENABLE_SAME_CELL_PAIR_FORCE 0
#endif

#endif // GSPH_COMPILE_CONFIG_H_
